apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter
  namespace: openshift-vsphere-infra
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vmware-exporter
      k8s-app: vmware-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vmware-exporter
        k8s-app: vmware-exporter
        release: vmware-exporter
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: vmware-exporter-config
        - secretRef:
            name: vmware-exporter-password
        image: quay.io/jcallen/vmware_exporter:add_metrics
        imagePullPolicy: Always
        name: vmware-exporter
        ports:
        - containerPort: 9272
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
