apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: vmware-exporter
  name: metrics
  namespace: openshift-vsphere-infra
spec:
  ports:
  - name: metrics
    port: 9272
    protocol: TCP
    targetPort: 9272
  selector:
    k8s-app: vmware-exporter
  sessionAffinity: None
  type: ClusterIP
